name: Engine
version: '${project.version}'
main: net.rebix.engine.Main
api-version: 1.18
description: My plugin engine to improve coding


commands:
  test:
    description: "the test command"
  writedefaultcfg:
    description: "writes the default cfg"
  /r:
    description: "reloads the plugins"
  /item:
    description: "custom item"
